#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    sum=0
    for i in range(len(arr)):
        mini=min(arr[i-1],arr[i])
        maxi=max(arr[i-1],arr[i])
        sum+=mini
    print(sum ,sum+max) 
if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
